version: '2'
services:
  web:
    env_file: .env
    image: mueno/togelack
    ports:
      - 3031:3000
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    restart: always
  redis:
    image: redis
    restart: always
